apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ascendion-assignment-app:latest
          imagePullPolicy: Never   # required for the minikube setup
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: web-secrets
                key: URL
          ports:
            - containerPort: 8000
      initContainers:
        - name: init
          image: ascendion-assignment-app:latest
          imagePullPolicy: Never   # required for the minikube setup
          command: ["python", "syncdb.py"]
          env:
          - name: DB_URL
            valueFrom:
              secretKeyRef:
                name: web-secrets
                key: URL
